export enum Habitats {
  padrao = '/assets/images/padrao.png',
  grassland = '/assets/images/grassland2.png',
  forest = '/assets/images/forest1.png',
  cave = '/assets/images/cave2.png',
  mountain = '/assets/images/mountain1.png',
  rough_terrain = '/assets/images/rough_terrain2.png',
  rocks = '/assets/images/rough_terrain3.png',
  waters_edge = '/assets/images/waters_edge1.png',
  river = '/assets/images/waters_edge2.png',
  deep_sea = '/assets/images/sea1.png',
  sea = '/assets/images/sea2.png',
  beach = '/assets/images/beach.png',
  urban = '/assets/images/urban1.png',
  rare = '/assets/images/rare.png',
  iceland = '/assets/images/cave3.png',
  high_mountain = '/assets/images/mountain2.png',
  dark_cave = '/assets/images/cave1.png',
  dark_forest = '/assets/images/forest2.png',
  sky = '/assets/images/sky.png',
}
